### ISSUE TITLE
Bug: Submitting a job to a nonexistent namespace should not retry

### ISSUE THREAD

**Issue by kannon92** [G-Research/armada#1441]
You must create the namespace first before submitting a job.  If a job can't be submitted because the namespace doesn't exist, then we should just fail the job on the first submission.  Currently, it retries.  We should update the executor to detect errors like this and fail the submission process. 

A reproducible example is below:

If you submit this job with armadactl, it looks like it is succesful.  There are errors in the executor logs saying the job failed to submit.  
```
queue: test
jobSetId: job-set-1
jobs:
  - priority: 0
    namespace: test-1
    podSpec:
      terminationGracePeriodSeconds: 0
      restartPolicy: Never
      containers:
        - name: sleep
          imagePullPolicy: IfNotPresent
          image: alpine:latest
          command:
            - sh
            - -c
          args:
            - sleep $(( (RANDOM % 30) + 30 ))
          resources:
            limits:
              memory: 64Mi
              cpu: 150m
            requests:
              memory: 64Mi
              cpu: 150m
```
