### ISSUE TITLE
JobService does not correctly read the armadactl config options.

### ISSUE THREAD

**Issue by kannon92** [G-Research/armada#1470]
@iJanki-gr discovered that we aren't able to use the armadactl config options or even place them in the jobservice config file.  

We will go with adding the config options into the config file:

```
grpcPort: 60003
httpPort: 8090
subscribeJobSetTime: 10000
databasePath: "/tmp/jobservice.db"
grpc:
  keepaliveParams:
    maxConnectionIdle: 5m
    time: 2h
    timeout: 20s
  keepaliveEnforcementPolicy:
    minTime: 5m
    permitWithoutStream: false

apiConnection:
    armadaUrl: armada-url

    openIdPasswordAuth:
        providerUrl: "https://signin/"
        clientId: client
        scopes:
            - armada-qa
        username: username
```

JobService should use a config file like this to populate the apiConnection field and allow connections to occur.
